// src/main/resources/public/examples/ShipWidget.svelte
<!--
  ShipKit · Svelte example
  ========================
  ShipKit manages its own DOM inside the mount element, so Svelte just provides
  the container and drives the lifecycle. shipkit.js is a UMD global
  (window.ShipKit), not an ES module — load it once in your app shell:

    Self-host:  <script src="/js/shipkit.js"></script>  in app.html
    Managed:    the CDN <script src="https://cdn.liftedholdings.com/shipkit.js"
                integrity="sha384-…" crossorigin="anonymous"> tag (no data-mount,
                so it does NOT auto-init).

  Then use <ShipWidget ... /> anywhere. Events are forwarded via createEventDispatcher.
-->
<script>
  import { onMount, onDestroy, createEventDispatcher } from 'svelte';

  export let endpoint = '/api';
  export let apiKey = undefined;
  export let managedKey = undefined;
  export let theme = 'dark';
  export let from = undefined;
  export let parcel = undefined;

  const dispatch = createEventDispatcher();
  let mount;
  let widget;

  onMount(() => {
    if (!mount || !window.ShipKit) return;
    widget = window.ShipKit.init({
      mount,
      // managedKey routes to Lifted's hosted API; otherwise talk to your endpoint.
      // Both are publishable pk_live_… keys (browser-safe, ShipKit-Api-Key header).
      ...(managedKey ? { managedKey } : { endpoint, apiKey }),
      theme,
      from,
      parcel,
      onQuote: (q) => dispatch('quote', q),
      onPurchase: (label) => dispatch('purchase', label),
      onError: (err) => dispatch('error', err),
    });
  });

  onDestroy(() => widget?.destroy());
</script>

<div bind:this={mount} aria-label="ShipKit shipping"></div>

<!--
  Usage:

    <script>
      import ShipWidget from './ShipWidget.svelte';
    </script>

    <ShipWidget
      endpoint="/api"
      apiKey="pk_live_your_publishable_key"
      on:purchase={(e) => console.log('bought', e.detail.trackingCode)}
      on:error={(e) => console.warn(e.detail.stage, e.detail.message)}
    />

    <!-- Managed tier (no backend): -->
    <ShipWidget managedKey="pk_live_your_publishable_key" on:purchase={onLabel} />
-->

// src/main/resources/public/examples/ShipWidget.vue
<!--
  ShipKit · Vue 3 example (<script setup>)
  ========================================
  ShipKit manages its own DOM inside the mount element, so Vue just provides the
  container and drives the lifecycle.

  Load the script first (self-host: /js/shipkit.js in index.html; managed: the
  CDN <script src="https://cdn.liftedholdings.com/shipkit.js" integrity="sha384-…"
  crossorigin="anonymous"> without data-mount). It attaches window.ShipKit.

  Then use <ShipWidget /> anywhere.
-->
<template>
  <div ref="mount" aria-label="ShipKit shipping"></div>
</template>

<script setup>
import { ref, onMounted, onBeforeUnmount } from 'vue';

const props = defineProps({
  endpoint: { type: String, default: '/api' },
  apiKey: { type: String, default: undefined },
  managedKey: { type: String, default: undefined },
  theme: { type: String, default: 'dark' },
  from: { type: Object, default: undefined },
  parcel: { type: Object, default: undefined },
});

const emit = defineEmits(['quote', 'purchase', 'error']);
const mount = ref(null);

onMounted(() => {
  if (!mount.value || !window.ShipKit) return;
  window.ShipKit.init({
    mount: mount.value,
    // managedKey routes to Lifted's hosted API; otherwise talk to your endpoint with
    // a self-host apiKey. Both are ShipKit publishable pk_live_… keys, browser-safe (ShipKit-Api-Key header).
    ...(props.managedKey ? { managedKey: props.managedKey } : { endpoint: props.endpoint, apiKey: props.apiKey }),
    theme: props.theme,
    from: props.from,
    parcel: props.parcel,
    onQuote: (q) => emit('quote', q),
    onPurchase: (label) => emit('purchase', label),
    onError: (err) => emit('error', err),
  });
});

onBeforeUnmount(() => {
  if (mount.value) mount.value.innerHTML = '';
});
</script>

<!--
  Usage:

    <ShipWidget
      endpoint="/api"
      theme="dark"
      @purchase="(label) => (window.location = label.labelUrl)"
      @error="(err) => notify(err.message)"
    />

    <!-- Self-host with a key: -->
    <ShipWidget endpoint="/api" api-key="pk_live_…" @purchase="onLabel" />

    <!-- Managed tier: -->
    <ShipWidget managed-key="pk_live_…" @purchase="onLabel" />
-->
